# 02 - Kaggle Supervised Baseline Runner

This notebook runs the four supervised baseline experiments on Kaggle GPU:

- `resnet18_none`
- `resnet18_imagenet`
- `vit_s16_none`
- `vit_s16_imagenet`

The notebook only prepares the Kaggle environment and calls repository scripts. It does not contain model training logic.

## 1. Enable Kaggle GPU

Before running, open **Settings** in Kaggle and select a GPU accelerator. T4 is enough for these baseline runs.

In [ ]:
from pathlib import Path
import json
import os
import shutil
import subprocess
import sys
import pandas as pd

print('Python:', sys.version)
print('Working directory:', Path.cwd())

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Working directory: /kaggle/working

## 2. Clone Or Pull Repository

This keeps the Kaggle working directory synchronized with the GitHub repository.

In [ ]:
REPO_URL = 'https://github.com/tlinhevg05/contrastive-synthesis-medcls_CVProject.git'
REPO_ROOT = Path('/kaggle/working/contrastive-synthesis-medcls_CVProject')

if REPO_ROOT.exists():
    subprocess.run(['git', '-C', str(REPO_ROOT), 'pull'], check=True)
else:
    subprocess.run(['git', 'clone', REPO_URL, str(REPO_ROOT)], check=True)

os.chdir(REPO_ROOT)
print('REPO_ROOT:', REPO_ROOT)

Cloning into '/kaggle/working/contrastive-synthesis-medcls_CVProject'...

REPO_ROOT: /kaggle/working/contrastive-synthesis-medcls_CVProject

Updating files: 100% (21260/21260), done.

## 3. Install Minimal Dependencies

Kaggle already provides PyTorch. This cell installs only the packages commonly needed by the training/evaluation scripts.

In [ ]:
subprocess.run([
    sys.executable, '-m', 'pip', 'install', '-q',
    'timm', 'scikit-learn', 'matplotlib', 'pandas', 'Pillow', 'pyyaml'
], check=True)

import torch
print('Torch:', torch.__version__)
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 94.9 MB/s eta 0:00:00

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.

Torch: 2.10.0+cu128
CUDA available: True
GPU: Tesla T4

## 4. Editable Runner Variables

Set the Kaggle dataset path and choose which baseline experiments to run. Add your Kaggle dataset named `medcls-cvproject` from the right panel before running data checks.

In [ ]:
# Kaggle dataset should contain:
# /kaggle/input/medcls-cvproject/data/processed/labelled_4232
# /kaggle/input/medcls-cvproject/data/manifests/train.csv, val.csv, test.csv
DATA_ROOT = Path('/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data')
LABELLED_SOURCE = DATA_ROOT / 'processed/labelled_4232'
MANIFEST_SOURCE = DATA_ROOT / 'manifests'

OUTPUT_ROOT = Path('/kaggle/working/results/experiments')

RUN_RESNET_NONE = True
RUN_RESNET_IMAGENET = True
RUN_VIT_NONE = True
RUN_VIT_IMAGENET = True

# Use 1 for smoke test. Use None for config/default epochs.
EPOCH_OVERRIDE = None
NUM_WORKERS = 2

print('DATA_ROOT:', DATA_ROOT)
print('LABELLED_SOURCE exists:', LABELLED_SOURCE.exists())
print('MANIFEST_SOURCE exists:', MANIFEST_SOURCE.exists())
print('OUTPUT_ROOT:', OUTPUT_ROOT)

DATA_ROOT: /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data
LABELLED_SOURCE exists: True
MANIFEST_SOURCE exists: True
OUTPUT_ROOT: /kaggle/working/results/experiments

## 5. Link Data And Manifests

The repo scripts expect data under `data/processed` and manifests under `data/manifests`. This cell symlinks Kaggle input data into the cloned repository when available.

In [ ]:
def replace_path(target: Path, source: Path):
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() or target.is_symlink():
        if target.is_symlink() or target.is_file():
            target.unlink()
        else:
            shutil.rmtree(target)
    if source.exists():
        os.symlink(source, target, target_is_directory=source.is_dir())
        print('Linked:', target, '->', source)
    else:
        print('WARNING: source missing:', source)

replace_path(REPO_ROOT / 'data/processed/labelled_4232', LABELLED_SOURCE)

(REPO_ROOT / 'data/manifests').mkdir(parents=True, exist_ok=True)
for name in ['train.csv', 'val.csv', 'test.csv', 'labelled_all.csv', 'split_summary.json']:
    src = MANIFEST_SOURCE / name
    dst = REPO_ROOT / 'data/manifests' / name
    if src.exists():
        if dst.exists() or dst.is_symlink():
            dst.unlink()
        os.symlink(src, dst)
        print('Linked manifest:', dst, '->', src)
    elif dst.exists():
        print('Using repo manifest:', dst)
    else:
        print('WARNING: missing manifest:', src)

print('\nRepository data snapshot:')
subprocess.run(['find', 'data', '-maxdepth', '3', '-type', 'd'], check=False)
subprocess.run(['ls', '-lh', 'data/manifests'], check=False)

Linked: /kaggle/working/contrastive-synthesis-medcls_CVProject/data/processed/labelled_4232 -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/processed/labelled_4232
Linked manifest: /kaggle/working/contrastive-synthesis-medcls_CVProject/data/manifests/train.csv -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/train.csv
Linked manifest: /kaggle/working/contrastive-synthesis-medcls_CVProject/data/manifests/val.csv -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/val.csv
Linked manifest: /kaggle/working/contrastive-synthesis-medcls_CVProject/data/manifests/test.csv -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/test.csv
Linked manifest: /kaggle/working/contrastive-synthesis-medcls_CVProject/data/manifests/labelled_all.csv -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/labelled_all.csv
Linked manifest: /kaggle/working/contrastive-synthesis-medcls_CVProject/data/manifests/split_summary.json -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/split_summary.json

Repository data snapshot:
data
data/manifests
data/processed
data/processed/unlabelled_16934
data/processed/unlabelled_16934/images
total 456K
lrwxrwxrwx 1 root root   82 Jun  9 22:39 labelled_all.csv -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/labelled_all.csv
lrwxrwxrwx 1 root root   84 Jun  9 22:39 split_summary.json -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/split_summary.json
-rw-r--r-- 1 root root 436K Jun  9 22:39 synthetic_dcgan.csv
lrwxrwxrwx 1 root root   74 Jun  9 22:39 test.csv -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/test.csv
lrwxrwxrwx 1 root root   75 Jun  9 22:39 train.csv -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/train.csv
lrwxrwxrwx 1 root root   73 Jun  9 22:39 val.csv -> /kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/val.csv

CompletedProcess(args=['ls', '-lh', 'data/manifests'], returncode=0)

## 6. Lightweight Checks

These checks should pass before launching training.

In [ ]:
from pathlib import Path
import subprocess

print('Kaggle input root:')
subprocess.run(['find', '/kaggle/input', '-maxdepth', '4', '-type', 'd'], check=False)

print('\nSearch labelled_4232:')
matches = list(Path('/kaggle/input').rglob('labelled_4232'))
print(matches)

print('\nSearch manifests:')
matches = list(Path('/kaggle/input').rglob('manifests'))
print(matches)

print('\nSearch csv files:')
csvs = list(Path('/kaggle/input').rglob('*.csv'))
for p in csvs[:30]:
    print(p)

Kaggle input root:

Search labelled_4232:
/kaggle/input
/kaggle/input/datasets
/kaggle/input/datasets/tlinhevg05
/kaggle/input/datasets/tlinhevg05/medcls-cvproject
/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data
[PosixPath('/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/processed/labelled_4232')]

Search manifests:
[PosixPath('/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests')]

Search csv files:
/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/synthetic_dcgan.csv
/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/val.csv
/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/labelled_all.csv
/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/train.csv
/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/manifests/test.csv
/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/processed/labelled_4232_manifest.csv
/kaggle/input/datasets/tlinhevg05/medcls-cvproject/data/processed/unlabelled_16934_manifest.csv

In [ ]:
subprocess.run([sys.executable, 'scripts/check_experiment_inputs.py'], check=True)
subprocess.run([
    sys.executable, '-m', 'py_compile',
    'scripts/run_classification_resnet.py',
    'scripts/evaluate_classification_resnet.py',
    'scripts/run_classification_vit.py',
    'scripts/evaluate_classification_vit.py',
], check=True)

Experiment Input Check Report
=============================
[PASS] common config
  - loaded configs/experiments/common.yaml
[PASS] fixed supervised manifests
  - train: {'COVID': 578, 'Lung_Opacity': 961, 'Viral_Pneumonia': 215, 'Normal': 1630} total=3384
  - val: {'COVID': 72, 'Lung_Opacity': 120, 'Viral_Pneumonia': 26, 'Normal': 203} total=421
  - test: {'COVID': 73, 'Lung_Opacity': 121, 'Viral_Pneumonia': 28, 'Normal': 205} total=427
[PASS] experiment config files
[PASS] resnet18_covidqu
  - planned output_dir: results/experiments/resnet18_covidqu
[PASS] resnet18_covidqu_syn
  - synthetic_dcgan: {'COVID': 1000, 'Lung_Opacity': 1000, 'Viral_Pneumonia': 1000, 'Normal': 1000} total=4000
  - planned output_dir: results/experiments/resnet18_covidqu_syn
[PASS] resnet18_imagenet
  - no contrastive pretraining data required
  - planned output_dir: results/experiments/resnet18_imagenet
[PASS] resnet18_imagenet_covidqu
  - planned output_dir: results/experiments/resnet18_imagenet_covidqu
[PASS] resnet18_imagenet_covidqu_syn
  - synthetic_dcgan: {'COVID': 1000, 'Lung_Opacity': 1000, 'Viral_Pneumonia': 1000, 'Normal': 1000} total=4000
  - planned output_dir: results/experiments/resnet18_imagenet_covidqu_syn
[PASS] resnet18_none
  - no contrastive pretraining data required
  - planned output_dir: results/experiments/resnet18_none
[PASS] vit_s16_covidqu
  - planned output_dir: results/experiments/vit_s16_covidqu
[PASS] vit_s16_covidqu_syn
  - synthetic_dcgan: {'COVID': 1000, 'Lung_Opacity': 1000, 'Viral_Pneumonia': 1000, 'Normal': 1000} total=4000
  - planned output_dir: results/experiments/vit_s16_covidqu_syn
[PASS] vit_s16_imagenet
  - no contrastive pretraining data required
  - planned output_dir: results/experiments/vit_s16_imagenet
[PASS] vit_s16_imagenet_covidqu
  - planned output_dir: results/experiments/vit_s16_imagenet_covidqu
[PASS] vit_s16_imagenet_covidqu_syn
  - synthetic_dcgan: {'COVID': 1000, 'Lung_Opacity': 1000, 'Viral_Pneumonia': 1000, 'Normal': 1000} total=4000
  - planned output_dir: results/experiments/vit_s16_imagenet_covidqu_syn
[PASS] vit_s16_none
  - no contrastive pretraining data required
  - planned output_dir: results/experiments/vit_s16_none

Summary
=======
PASS: 15
WARNING: 0
FAIL: 0

CompletedProcess(args=['/usr/bin/python3', '-m', 'py_compile', 'scripts/run_classification_resnet.py', 'scripts/evaluate_classification_resnet.py', 'scripts/run_classification_vit.py', 'scripts/evaluate_classification_vit.py'], returncode=0)

## 7. Helper Function

In [ ]:
def run_cmd(cmd):
    print('Running:')
    print(' '.join(map(str, cmd)))
    subprocess.run(list(map(str, cmd)), check=True)

def epoch_args():
    return [] if EPOCH_OVERRIDE is None else ['--epochs', str(EPOCH_OVERRIDE)]

def show_metrics(experiment_id):
    metrics_path = OUTPUT_ROOT / experiment_id / 'metrics.json'
    if not metrics_path.exists():
        print('Missing metrics:', metrics_path)
        return None
    metrics = json.loads(metrics_path.read_text())
    row = {'experiment_id': experiment_id, **metrics}
    display(pd.DataFrame([row]))
    return row

## 8. Experiment: resnet18_none

Train ResNet18 from random initialization on the fixed real labeled train/val/test manifests.

In [ ]:
EXP = 'resnet18_none'
if RUN_RESNET_NONE:
    run_cmd([
        sys.executable, 'scripts/run_classification_resnet.py',
        '--config', 'configs/experiments/resnet18/none.yaml',
        '--manifest-dir', 'data/manifests',
        '--output-dir', OUTPUT_ROOT / EXP,
        '--num-workers', NUM_WORKERS,
        *epoch_args(),
    ])
    show_metrics(EXP)
else:
    print('Skipping', EXP)

Running:
/usr/bin/python3 scripts/run_classification_resnet.py --config configs/experiments/resnet18/none.yaml --manifest-dir data/manifests --output-dir /kaggle/working/results/experiments/resnet18_none --num-workers 2
Epoch 1/70 train_loss=0.7794 val_loss=0.9030 val_acc=0.6437 val_f1_macro=0.6379
Epoch 2/70 train_loss=0.5383 val_loss=0.7481 val_acc=0.6960 val_f1_macro=0.7158
Epoch 3/70 train_loss=0.4357 val_loss=0.5735 val_acc=0.8052 val_f1_macro=0.8079
Epoch 4/70 train_loss=0.3596 val_loss=0.7348 val_acc=0.7672 val_f1_macro=0.7471
Epoch 5/70 train_loss=0.2996 val_loss=0.5304 val_acc=0.8147 val_f1_macro=0.8129
Epoch 6/70 train_loss=0.2250 val_loss=0.5552 val_acc=0.8076 val_f1_macro=0.8212
Epoch 7/70 train_loss=0.2013 val_loss=0.8958 val_acc=0.7886 val_f1_macro=0.7635
Epoch 8/70 train_loss=0.1762 val_loss=0.5889 val_acc=0.7815 val_f1_macro=0.7856
Epoch 9/70 train_loss=0.1296 val_loss=0.8919 val_acc=0.7078 val_f1_macro=0.7335
Epoch 10/70 train_loss=0.0998 val_loss=0.6055 val_acc=0.8361 val_f1_macro=0.8148
Epoch 11/70 train_loss=0.0966 val_loss=0.7483 val_acc=0.7791 val_f1_macro=0.7789
Epoch 12/70 train_loss=0.0916 val_loss=0.8009 val_acc=0.8052 val_f1_macro=0.8078
Epoch 13/70 train_loss=0.0654 val_loss=0.6281 val_acc=0.8314 val_f1_macro=0.8287
Epoch 14/70 train_loss=0.0505 val_loss=0.7232 val_acc=0.7648 val_f1_macro=0.7660
Epoch 15/70 train_loss=0.0555 val_loss=0.6421 val_acc=0.8290 val_f1_macro=0.8348
Epoch 16/70 train_loss=0.0554 val_loss=0.6989 val_acc=0.7981 val_f1_macro=0.8056
Epoch 17/70 train_loss=0.0716 val_loss=0.8413 val_acc=0.8242 val_f1_macro=0.8077
Epoch 18/70 train_loss=0.0505 val_loss=0.8057 val_acc=0.8361 val_f1_macro=0.8294
Epoch 19/70 train_loss=0.0444 val_loss=0.6824 val_acc=0.8266 val_f1_macro=0.8267
Epoch 20/70 train_loss=0.0388 val_loss=0.7582 val_acc=0.8409 val_f1_macro=0.8335
Epoch 21/70 train_loss=0.0575 val_loss=1.0398 val_acc=0.7791 val_f1_macro=0.7784
Epoch 22/70 train_loss=0.0488 val_loss=0.7268 val_acc=0.8195 val_f1_macro=0.8174
Epoch 23/70 train_loss=0.0500 val_loss=0.9339 val_acc=0.8005 val_f1_macro=0.8051
Epoch 24/70 train_loss=0.0275 val_loss=0.7470 val_acc=0.8290 val_f1_macro=0.8342
Epoch 25/70 train_loss=0.0257 val_loss=0.7392 val_acc=0.8290 val_f1_macro=0.8243
Epoch 26/70 train_loss=0.0170 val_loss=0.6762 val_acc=0.8385 val_f1_macro=0.8388
Epoch 27/70 train_loss=0.0177 val_loss=0.7115 val_acc=0.8409 val_f1_macro=0.8381
Epoch 28/70 train_loss=0.0467 val_loss=0.6611 val_acc=0.8171 val_f1_macro=0.8271
Epoch 29/70 train_loss=0.0263 val_loss=0.7540 val_acc=0.8409 val_f1_macro=0.8364
Epoch 30/70 train_loss=0.0459 val_loss=0.9216 val_acc=0.7743 val_f1_macro=0.7855
Epoch 31/70 train_loss=0.0452 val_loss=0.9248 val_acc=0.7957 val_f1_macro=0.8092
Epoch 32/70 train_loss=0.0391 val_loss=0.8114 val_acc=0.8266 val_f1_macro=0.8258
Epoch 33/70 train_loss=0.0276 val_loss=0.7251 val_acc=0.8124 val_f1_macro=0.8225
Epoch 34/70 train_loss=0.0316 val_loss=0.6472 val_acc=0.8527 val_f1_macro=0.8565
Epoch 35/70 train_loss=0.0243 val_loss=0.9150 val_acc=0.7862 val_f1_macro=0.7884
Epoch 36/70 train_loss=0.0273 val_loss=0.8433 val_acc=0.8100 val_f1_macro=0.7992
Epoch 37/70 train_loss=0.0370 val_loss=0.8801 val_acc=0.8005 val_f1_macro=0.8015
Epoch 38/70 train_loss=0.0356 val_loss=0.7341 val_acc=0.8504 val_f1_macro=0.8494
Epoch 39/70 train_loss=0.0338 val_loss=0.8099 val_acc=0.8314 val_f1_macro=0.8217
Epoch 40/70 train_loss=0.0250 val_loss=0.6917 val_acc=0.8432 val_f1_macro=0.8450
Epoch 41/70 train_loss=0.0269 val_loss=0.8534 val_acc=0.8361 val_f1_macro=0.8461
Epoch 42/70 train_loss=0.0381 val_loss=1.2375 val_acc=0.7458 val_f1_macro=0.7115
Epoch 43/70 train_loss=0.0628 val_loss=1.1548 val_acc=0.7340 val_f1_macro=0.7548
Epoch 44/70 train_loss=0.0253 val_loss=0.7444 val_acc=0.8622 val_f1_macro=0.8644
Epoch 45/70 train_loss=0.0256 val_loss=0.8399 val_acc=0.8219 val_f1_macro=0.8117
Epoch 46/70 train_loss=0.0367 val_loss=0.9016 val_acc=0.8171 val_f1_macro=0.8019
Epoch 47/70 train_loss=0.0196 val_loss=0.7714 val_acc=0.8622 val_f1_macro=0.8611
Epoch 48/70 train_loss=0.0141 val_loss=0.7561 val_acc=0.8504 val_f1_macro=0.8464
Epoch 49/70 train_loss=0.0080 val_loss=0.7014 val_acc=0.8694 val_f1_macro=0.8744
Epoch 50/70 train_loss=0.0053 val_loss=0.7484 val_acc=0.8622 val_f1_macro=0.8625
Epoch 51/70 train_loss=0.0065 val_loss=0.8373 val_acc=0.8266 val_f1_macro=0.8313
Epoch 52/70 train_loss=0.0050 val_loss=0.8075 val_acc=0.8504 val_f1_macro=0.8494
Epoch 53/70 train_loss=0.0126 val_loss=1.1941 val_acc=0.8076 val_f1_macro=0.7861
Epoch 54/70 train_loss=0.0375 val_loss=0.9314 val_acc=0.8171 val_f1_macro=0.8120
Epoch 55/70 train_loss=0.0434 val_loss=0.8269 val_acc=0.8290 val_f1_macro=0.8125
Epoch 56/70 train_loss=0.0314 val_loss=1.0927 val_acc=0.7815 val_f1_macro=0.7523
Epoch 57/70 train_loss=0.0276 val_loss=0.7637 val_acc=0.8361 val_f1_macro=0.8341
Epoch 58/70 train_loss=0.0234 val_loss=0.7021 val_acc=0.8551 val_f1_macro=0.8543
Epoch 59/70 train_loss=0.0240 val_loss=0.8887 val_acc=0.8147 val_f1_macro=0.8217
Epoch 60/70 train_loss=0.0403 val_loss=0.8632 val_acc=0.8456 val_f1_macro=0.8386
Epoch 61/70 train_loss=0.0125 val_loss=0.8627 val_acc=0.8385 val_f1_macro=0.8515
Epoch 62/70 train_loss=0.0204 val_loss=0.9081 val_acc=0.8266 val_f1_macro=0.8186
Epoch 63/70 train_loss=0.0265 val_loss=0.8054 val_acc=0.8337 val_f1_macro=0.8052
Epoch 64/70 train_loss=0.0112 val_loss=0.9079 val_acc=0.8480 val_f1_macro=0.8372
Epoch 65/70 train_loss=0.0100 val_loss=0.7850 val_acc=0.8385 val_f1_macro=0.8341
Epoch 66/70 train_loss=0.0140 val_loss=0.8705 val_acc=0.8432 val_f1_macro=0.8281
Epoch 67/70 train_loss=0.0077 val_loss=0.7771 val_acc=0.8290 val_f1_macro=0.8284
Epoch 68/70 train_loss=0.0071 val_loss=0.7544 val_acc=0.8575 val_f1_macro=0.8628
Epoch 69/70 train_loss=0.0087 val_loss=0.8938 val_acc=0.8504 val_f1_macro=0.8564
Epoch 70/70 train_loss=0.0223 val_loss=0.8080 val_acc=0.8432 val_f1_macro=0.8455
Saved baseline outputs to /kaggle/working/results/experiments/resnet18_none
{'accuracy': 0.882903981264637, 'precision_macro': 0.9092863889313787, 'recall_macro': 0.8905509549831149, 'f1_macro': 0.8980919919135022, 'precision_weighted': 0.8843802223614932, 'recall_weighted': 0.882903981264637, 'f1_weighted': 0.8816246838529916, 'best_epoch': 49, 'best_val_f1_macro': 0.8743576952943952}

,experiment_id,accuracy,precision_macro,recall_macro,f1_macro,precision_weighted,recall_weighted,f1_weighted,best_epoch,best_val_f1_macro
0,resnet18_none,0.882904,0.909286,0.890551,0.898092,0.88438,0.882904,0.881625,49,0.874358

## 9. Experiment: resnet18_imagenet

Fine-tune ImageNet-pretrained ResNet18 on the fixed real labeled train/val/test manifests.

In [ ]:
EXP = 'resnet18_imagenet'
if RUN_RESNET_IMAGENET:
    run_cmd([
        sys.executable, 'scripts/run_classification_resnet.py',
        '--config', 'configs/experiments/resnet18/imagenet.yaml',
        '--manifest-dir', 'data/manifests',
        '--output-dir', OUTPUT_ROOT / EXP,
        '--num-workers', NUM_WORKERS,
        *epoch_args(),
    ])
    show_metrics(EXP)
else:
    print('Skipping', EXP)

Running:
/usr/bin/python3 scripts/run_classification_resnet.py --config configs/experiments/resnet18/imagenet.yaml --manifest-dir data/manifests --output-dir /kaggle/working/results/experiments/resnet18_imagenet --num-workers 2
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth

100%|██████████| 44.7M/44.7M [00:00<00:00, 143MB/s]

Epoch 1/70 train_loss=0.7623 val_loss=0.5737 val_acc=0.8005 val_f1_macro=0.7927
Epoch 2/70 train_loss=0.4226 val_loss=0.4227 val_acc=0.8337 val_f1_macro=0.8294
Epoch 3/70 train_loss=0.3018 val_loss=0.3598 val_acc=0.8670 val_f1_macro=0.8739
Epoch 4/70 train_loss=0.2355 val_loss=0.3260 val_acc=0.8789 val_f1_macro=0.8840
Epoch 5/70 train_loss=0.1917 val_loss=0.3105 val_acc=0.8860 val_f1_macro=0.8892
Epoch 6/70 train_loss=0.1554 val_loss=0.2959 val_acc=0.8979 val_f1_macro=0.9011
Epoch 7/70 train_loss=0.1309 val_loss=0.2975 val_acc=0.9026 val_f1_macro=0.9073
Epoch 8/70 train_loss=0.1173 val_loss=0.2827 val_acc=0.9074 val_f1_macro=0.9126
Epoch 9/70 train_loss=0.0888 val_loss=0.2883 val_acc=0.9050 val_f1_macro=0.9124
Epoch 10/70 train_loss=0.0721 val_loss=0.2857 val_acc=0.9097 val_f1_macro=0.9214
Epoch 11/70 train_loss=0.0604 val_loss=0.2842 val_acc=0.9121 val_f1_macro=0.9234
Epoch 12/70 train_loss=0.0471 val_loss=0.2867 val_acc=0.9050 val_f1_macro=0.9145
Epoch 13/70 train_loss=0.0416 val_loss=0.2911 val_acc=0.9050 val_f1_macro=0.9140
Epoch 14/70 train_loss=0.0306 val_loss=0.2901 val_acc=0.9121 val_f1_macro=0.9170
Epoch 15/70 train_loss=0.0345 val_loss=0.3049 val_acc=0.9074 val_f1_macro=0.9180
Epoch 16/70 train_loss=0.0261 val_loss=0.3168 val_acc=0.9097 val_f1_macro=0.9147
Epoch 17/70 train_loss=0.0234 val_loss=0.2993 val_acc=0.9050 val_f1_macro=0.9073
Epoch 18/70 train_loss=0.0181 val_loss=0.3092 val_acc=0.9074 val_f1_macro=0.9204
Epoch 19/70 train_loss=0.0206 val_loss=0.3092 val_acc=0.9050 val_f1_macro=0.9144
Epoch 20/70 train_loss=0.0186 val_loss=0.2996 val_acc=0.9097 val_f1_macro=0.9180
Epoch 21/70 train_loss=0.0131 val_loss=0.3154 val_acc=0.9145 val_f1_macro=0.9250
Epoch 22/70 train_loss=0.0142 val_loss=0.3168 val_acc=0.9050 val_f1_macro=0.9132
Epoch 23/70 train_loss=0.0109 val_loss=0.3291 val_acc=0.9074 val_f1_macro=0.9199
Epoch 24/70 train_loss=0.0099 val_loss=0.3183 val_acc=0.9074 val_f1_macro=0.9158
Epoch 25/70 train_loss=0.0102 val_loss=0.3224 val_acc=0.9074 val_f1_macro=0.9187
Epoch 26/70 train_loss=0.0099 val_loss=0.3573 val_acc=0.8907 val_f1_macro=0.9084
Epoch 27/70 train_loss=0.0070 val_loss=0.3243 val_acc=0.9145 val_f1_macro=0.9271
Epoch 28/70 train_loss=0.0074 val_loss=0.3495 val_acc=0.9026 val_f1_macro=0.9222
Epoch 29/70 train_loss=0.0062 val_loss=0.3311 val_acc=0.9097 val_f1_macro=0.9269
Epoch 30/70 train_loss=0.0072 val_loss=0.3290 val_acc=0.9074 val_f1_macro=0.9204
Epoch 31/70 train_loss=0.0051 val_loss=0.3431 val_acc=0.9074 val_f1_macro=0.9253
Epoch 32/70 train_loss=0.0057 val_loss=0.3449 val_acc=0.9121 val_f1_macro=0.9249
Epoch 33/70 train_loss=0.0053 val_loss=0.3585 val_acc=0.9074 val_f1_macro=0.9213
Epoch 34/70 train_loss=0.0043 val_loss=0.3508 val_acc=0.9074 val_f1_macro=0.9243
Epoch 35/70 train_loss=0.0057 val_loss=0.3626 val_acc=0.9097 val_f1_macro=0.9266
Epoch 36/70 train_loss=0.0045 val_loss=0.3633 val_acc=0.9169 val_f1_macro=0.9322
Epoch 37/70 train_loss=0.0037 val_loss=0.3723 val_acc=0.9002 val_f1_macro=0.9148
Epoch 38/70 train_loss=0.0047 val_loss=0.3795 val_acc=0.9026 val_f1_macro=0.9161
Epoch 39/70 train_loss=0.0066 val_loss=0.3759 val_acc=0.9121 val_f1_macro=0.9258
Epoch 40/70 train_loss=0.0037 val_loss=0.3800 val_acc=0.9074 val_f1_macro=0.9213
Epoch 41/70 train_loss=0.0043 val_loss=0.3724 val_acc=0.9050 val_f1_macro=0.9087
Epoch 42/70 train_loss=0.0025 val_loss=0.3748 val_acc=0.9121 val_f1_macro=0.9175
Epoch 43/70 train_loss=0.0034 val_loss=0.3867 val_acc=0.9074 val_f1_macro=0.9253
Epoch 44/70 train_loss=0.0034 val_loss=0.3798 val_acc=0.9002 val_f1_macro=0.9155
Epoch 45/70 train_loss=0.0040 val_loss=0.4283 val_acc=0.8955 val_f1_macro=0.9017
Epoch 46/70 train_loss=0.0025 val_loss=0.3887 val_acc=0.9026 val_f1_macro=0.9176
Epoch 47/70 train_loss=0.0023 val_loss=0.3894 val_acc=0.9026 val_f1_macro=0.9113
Epoch 48/70 train_loss=0.0026 val_loss=0.4038 val_acc=0.9074 val_f1_macro=0.9155
Epoch 49/70 train_loss=0.0014 val_loss=0.3900 val_acc=0.9121 val_f1_macro=0.9243
Epoch 50/70 train_loss=0.0014 val_loss=0.3934 val_acc=0.9074 val_f1_macro=0.9224
Epoch 51/70 train_loss=0.0019 val_loss=0.4059 val_acc=0.9074 val_f1_macro=0.9167
Epoch 52/70 train_loss=0.0013 val_loss=0.3937 val_acc=0.9169 val_f1_macro=0.9235
Epoch 53/70 train_loss=0.0017 val_loss=0.3932 val_acc=0.9097 val_f1_macro=0.9232
Epoch 54/70 train_loss=0.0017 val_loss=0.3862 val_acc=0.9097 val_f1_macro=0.9188
Epoch 55/70 train_loss=0.0011 val_loss=0.3895 val_acc=0.9050 val_f1_macro=0.9133
Epoch 56/70 train_loss=0.0017 val_loss=0.3889 val_acc=0.9121 val_f1_macro=0.9244
Epoch 57/70 train_loss=0.0018 val_loss=0.4038 val_acc=0.9097 val_f1_macro=0.9232
Epoch 58/70 train_loss=0.0011 val_loss=0.3858 val_acc=0.9169 val_f1_macro=0.9281
Epoch 59/70 train_loss=0.0024 val_loss=0.4371 val_acc=0.9026 val_f1_macro=0.9123
Epoch 60/70 train_loss=0.0019 val_loss=0.4101 val_acc=0.9074 val_f1_macro=0.9167
Epoch 61/70 train_loss=0.0008 val_loss=0.4136 val_acc=0.9074 val_f1_macro=0.9176
Epoch 62/70 train_loss=0.0020 val_loss=0.4396 val_acc=0.9050 val_f1_macro=0.9179
Epoch 63/70 train_loss=0.0033 val_loss=0.4071 val_acc=0.9050 val_f1_macro=0.9153
Epoch 64/70 train_loss=0.0013 val_loss=0.4589 val_acc=0.8955 val_f1_macro=0.9063
Epoch 65/70 train_loss=0.0010 val_loss=0.4239 val_acc=0.9121 val_f1_macro=0.9236
Epoch 66/70 train_loss=0.0038 val_loss=0.4419 val_acc=0.9026 val_f1_macro=0.9140
Epoch 67/70 train_loss=0.0018 val_loss=0.4605 val_acc=0.9074 val_f1_macro=0.9125
Epoch 68/70 train_loss=0.0018 val_loss=0.4591 val_acc=0.9097 val_f1_macro=0.9181
Epoch 69/70 train_loss=0.0013 val_loss=0.4226 val_acc=0.9145 val_f1_macro=0.9203
Epoch 70/70 train_loss=0.0008 val_loss=0.4313 val_acc=0.9169 val_f1_macro=0.9234
Saved baseline outputs to /kaggle/working/results/experiments/resnet18_imagenet
{'accuracy': 0.9391100702576113, 'precision_macro': 0.9574352897043277, 'recall_macro': 0.9506714013138093, 'f1_macro': 0.9539367371858425, 'precision_weighted': 0.9392850973183203, 'recall_weighted': 0.9391100702576113, 'f1_weighted': 0.9390596561298025, 'best_epoch': 36, 'best_val_f1_macro': 0.9322322640321563}

,experiment_id,accuracy,precision_macro,recall_macro,f1_macro,precision_weighted,recall_weighted,f1_weighted,best_epoch,best_val_f1_macro
0,resnet18_imagenet,0.93911,0.957435,0.950671,0.953937,0.939285,0.93911,0.93906,36,0.932232

## 10. Experiment: vit_s16_none

Train ViT-S/16 from random initialization on the fixed real labeled train/val/test manifests.

In [ ]:
EXP = 'vit_s16_none'
if RUN_VIT_NONE:
    run_cmd([
        sys.executable, 'scripts/run_classification_vit.py',
        '--config', 'configs/experiments/vit_s16/none.yaml',
        '--manifest-dir', 'data/manifests',
        '--output-dir', OUTPUT_ROOT / EXP,
        '--num-workers', NUM_WORKERS,
        *epoch_args(),
    ])
    show_metrics(EXP)
else:
    print('Skipping', EXP)

Running:
/usr/bin/python3 scripts/run_classification_vit.py --config configs/experiments/vit_s16/none.yaml --manifest-dir data/manifests --output-dir /kaggle/working/results/experiments/vit_s16_none --num-workers 2
Epoch 1/50 train_loss=1.1640 val_loss=1.1104 val_acc=0.5392 val_f1_macro=0.3963
Epoch 2/50 train_loss=1.0515 val_loss=0.9895 val_acc=0.5748 val_f1_macro=0.3213
Epoch 3/50 train_loss=0.9752 val_loss=0.8833 val_acc=0.6413 val_f1_macro=0.5392
Epoch 4/50 train_loss=0.8969 val_loss=0.9094 val_acc=0.6128 val_f1_macro=0.5896
Epoch 5/50 train_loss=0.8538 val_loss=0.8358 val_acc=0.6651 val_f1_macro=0.5747
Epoch 6/50 train_loss=0.8078 val_loss=0.8056 val_acc=0.6841 val_f1_macro=0.6104
Epoch 7/50 train_loss=0.7618 val_loss=0.7978 val_acc=0.6722 val_f1_macro=0.5639
Epoch 8/50 train_loss=0.7164 val_loss=0.7232 val_acc=0.7150 val_f1_macro=0.6597
Epoch 9/50 train_loss=0.6845 val_loss=0.6348 val_acc=0.7672 val_f1_macro=0.7768
Epoch 10/50 train_loss=0.6373 val_loss=0.6478 val_acc=0.7458 val_f1_macro=0.7270
Epoch 11/50 train_loss=0.6061 val_loss=0.5657 val_acc=0.7672 val_f1_macro=0.7712
Epoch 12/50 train_loss=0.5754 val_loss=0.6337 val_acc=0.7340 val_f1_macro=0.7473
Epoch 13/50 train_loss=0.5848 val_loss=0.5934 val_acc=0.7672 val_f1_macro=0.7484
Epoch 14/50 train_loss=0.5480 val_loss=0.5696 val_acc=0.7767 val_f1_macro=0.7576
Epoch 15/50 train_loss=0.5005 val_loss=0.5954 val_acc=0.7791 val_f1_macro=0.7898
Epoch 16/50 train_loss=0.5126 val_loss=0.6460 val_acc=0.7648 val_f1_macro=0.7624
Epoch 17/50 train_loss=0.4868 val_loss=0.5398 val_acc=0.7743 val_f1_macro=0.7591
Epoch 18/50 train_loss=0.4333 val_loss=0.5508 val_acc=0.7957 val_f1_macro=0.7933
Epoch 19/50 train_loss=0.4369 val_loss=0.5977 val_acc=0.7743 val_f1_macro=0.7704
Epoch 20/50 train_loss=0.4131 val_loss=0.6175 val_acc=0.7506 val_f1_macro=0.7498
Epoch 21/50 train_loss=0.3978 val_loss=0.5724 val_acc=0.7696 val_f1_macro=0.7837
Epoch 22/50 train_loss=0.4136 val_loss=0.5825 val_acc=0.7838 val_f1_macro=0.7892
Epoch 23/50 train_loss=0.3665 val_loss=0.5625 val_acc=0.7910 val_f1_macro=0.7987
Epoch 24/50 train_loss=0.3579 val_loss=0.5508 val_acc=0.7957 val_f1_macro=0.8008
Epoch 25/50 train_loss=0.3741 val_loss=0.5173 val_acc=0.8124 val_f1_macro=0.8171
Epoch 26/50 train_loss=0.3492 val_loss=0.6086 val_acc=0.7815 val_f1_macro=0.7599
Epoch 27/50 train_loss=0.3159 val_loss=0.5713 val_acc=0.8005 val_f1_macro=0.8080
Epoch 28/50 train_loss=0.3170 val_loss=0.6415 val_acc=0.7838 val_f1_macro=0.7723
Epoch 29/50 train_loss=0.3062 val_loss=0.5813 val_acc=0.7696 val_f1_macro=0.7722
Epoch 30/50 train_loss=0.3017 val_loss=0.6372 val_acc=0.7743 val_f1_macro=0.7778
Epoch 31/50 train_loss=0.2758 val_loss=0.6610 val_acc=0.7981 val_f1_macro=0.7912
Epoch 32/50 train_loss=0.2787 val_loss=0.6176 val_acc=0.7886 val_f1_macro=0.7895
Epoch 33/50 train_loss=0.2888 val_loss=0.7810 val_acc=0.7577 val_f1_macro=0.7485
Epoch 34/50 train_loss=0.2575 val_loss=0.7002 val_acc=0.7815 val_f1_macro=0.7770
Epoch 35/50 train_loss=0.2632 val_loss=0.6103 val_acc=0.7838 val_f1_macro=0.7893
Epoch 36/50 train_loss=0.2700 val_loss=0.6142 val_acc=0.7862 val_f1_macro=0.7842
Epoch 37/50 train_loss=0.2169 val_loss=0.6319 val_acc=0.7553 val_f1_macro=0.7546
Epoch 38/50 train_loss=0.2636 val_loss=0.6433 val_acc=0.7981 val_f1_macro=0.8038
Epoch 39/50 train_loss=0.2232 val_loss=0.6484 val_acc=0.7815 val_f1_macro=0.7740
Epoch 40/50 train_loss=0.2098 val_loss=0.6466 val_acc=0.8100 val_f1_macro=0.8210
Epoch 41/50 train_loss=0.1972 val_loss=0.6878 val_acc=0.7743 val_f1_macro=0.7809
Epoch 42/50 train_loss=0.1900 val_loss=0.7205 val_acc=0.8029 val_f1_macro=0.7992
Epoch 43/50 train_loss=0.2109 val_loss=0.6649 val_acc=0.8052 val_f1_macro=0.8011
Epoch 44/50 train_loss=0.1845 val_loss=0.6793 val_acc=0.7886 val_f1_macro=0.7911
Epoch 45/50 train_loss=0.1969 val_loss=0.7444 val_acc=0.7767 val_f1_macro=0.7453
Epoch 46/50 train_loss=0.1773 val_loss=0.6647 val_acc=0.7910 val_f1_macro=0.7921
Epoch 47/50 train_loss=0.1798 val_loss=0.6853 val_acc=0.7886 val_f1_macro=0.7922
Epoch 48/50 train_loss=0.1552 val_loss=0.7624 val_acc=0.7672 val_f1_macro=0.7478
Epoch 49/50 train_loss=0.1584 val_loss=0.8143 val_acc=0.7957 val_f1_macro=0.7879
Epoch 50/50 train_loss=0.1822 val_loss=0.7424 val_acc=0.7886 val_f1_macro=0.7907
Saved baseline outputs to /kaggle/working/results/experiments/vit_s16_none
{'accuracy': 0.7775175644028103, 'precision_macro': 0.8278309387129392, 'recall_macro': 0.7627316503166972, 'f1_macro': 0.7869884513149662, 'precision_weighted': 0.7859646028501321, 'recall_weighted': 0.7775175644028103, 'f1_weighted': 0.7721041959524356, 'best_epoch': 40, 'best_val_f1_macro': 0.8209631605852934}

,experiment_id,accuracy,precision_macro,recall_macro,f1_macro,precision_weighted,recall_weighted,f1_weighted,best_epoch,best_val_f1_macro
0,vit_s16_none,0.777518,0.827831,0.762732,0.786988,0.785965,0.777518,0.772104,40,0.820963

## 11. Experiment: vit_s16_imagenet

Fine-tune ImageNet-pretrained ViT-S/16 on the fixed real labeled train/val/test manifests.

In [ ]:
EXP = 'vit_s16_imagenet'
if RUN_VIT_IMAGENET:
    run_cmd([
        sys.executable, 'scripts/run_classification_vit.py',
        '--config', 'configs/experiments/vit_s16/imagenet.yaml',
        '--manifest-dir', 'data/manifests',
        '--output-dir', OUTPUT_ROOT / EXP,
        '--num-workers', NUM_WORKERS,
        *epoch_args(),
    ])
    show_metrics(EXP)
else:
    print('Skipping', EXP)

Running:
/usr/bin/python3 scripts/run_classification_vit.py --config configs/experiments/vit_s16/imagenet.yaml --manifest-dir data/manifests --output-dir /kaggle/working/results/experiments/vit_s16_imagenet --num-workers 2
Epoch 1/50 train_loss=0.7012 val_loss=0.4470 val_acc=0.8385 val_f1_macro=0.8473
Epoch 2/50 train_loss=0.3035 val_loss=0.3675 val_acc=0.8646 val_f1_macro=0.8622
Epoch 3/50 train_loss=0.1755 val_loss=0.3313 val_acc=0.8765 val_f1_macro=0.8772
Epoch 4/50 train_loss=0.1063 val_loss=0.3683 val_acc=0.8717 val_f1_macro=0.8851
Epoch 5/50 train_loss=0.0892 val_loss=0.3016 val_acc=0.9026 val_f1_macro=0.9060
Epoch 6/50 train_loss=0.0420 val_loss=0.3555 val_acc=0.8907 val_f1_macro=0.8988
Epoch 7/50 train_loss=0.0276 val_loss=0.3329 val_acc=0.9026 val_f1_macro=0.9101
Epoch 8/50 train_loss=0.0241 val_loss=0.3476 val_acc=0.9121 val_f1_macro=0.9184
Epoch 9/50 train_loss=0.0303 val_loss=0.3689 val_acc=0.9002 val_f1_macro=0.9123
Epoch 10/50 train_loss=0.0108 val_loss=0.3767 val_acc=0.8955 val_f1_macro=0.8981
Epoch 11/50 train_loss=0.0046 val_loss=0.3861 val_acc=0.9026 val_f1_macro=0.9057
Epoch 12/50 train_loss=0.0055 val_loss=0.3971 val_acc=0.9050 val_f1_macro=0.9053
Epoch 13/50 train_loss=0.0016 val_loss=0.4232 val_acc=0.9145 val_f1_macro=0.9151
Epoch 14/50 train_loss=0.0019 val_loss=0.4078 val_acc=0.9026 val_f1_macro=0.9042
Epoch 15/50 train_loss=0.0013 val_loss=0.4230 val_acc=0.9074 val_f1_macro=0.9067
Epoch 16/50 train_loss=0.0008 val_loss=0.4416 val_acc=0.9121 val_f1_macro=0.9135
Epoch 17/50 train_loss=0.0007 val_loss=0.4420 val_acc=0.9097 val_f1_macro=0.9083
Epoch 18/50 train_loss=0.0006 val_loss=0.4531 val_acc=0.9121 val_f1_macro=0.9135
Epoch 19/50 train_loss=0.0005 val_loss=0.4475 val_acc=0.9097 val_f1_macro=0.9119
Epoch 20/50 train_loss=0.0005 val_loss=0.4592 val_acc=0.9121 val_f1_macro=0.9135
Epoch 21/50 train_loss=0.0004 val_loss=0.4639 val_acc=0.9097 val_f1_macro=0.9119
Epoch 22/50 train_loss=0.0004 val_loss=0.4677 val_acc=0.9121 val_f1_macro=0.9135
Epoch 23/50 train_loss=0.0003 val_loss=0.4755 val_acc=0.9121 val_f1_macro=0.9135
Epoch 24/50 train_loss=0.0003 val_loss=0.4739 val_acc=0.9097 val_f1_macro=0.9119
Epoch 25/50 train_loss=0.0003 val_loss=0.4753 val_acc=0.9074 val_f1_macro=0.9067
Epoch 26/50 train_loss=0.0003 val_loss=0.4921 val_acc=0.9121 val_f1_macro=0.9135
Epoch 27/50 train_loss=0.0002 val_loss=0.4895 val_acc=0.9097 val_f1_macro=0.9083
Epoch 28/50 train_loss=0.0002 val_loss=0.4939 val_acc=0.9121 val_f1_macro=0.9135
Epoch 29/50 train_loss=0.0002 val_loss=0.5011 val_acc=0.9121 val_f1_macro=0.9135
Epoch 30/50 train_loss=0.0002 val_loss=0.5070 val_acc=0.9121 val_f1_macro=0.9135
Epoch 31/50 train_loss=0.0002 val_loss=0.5080 val_acc=0.9121 val_f1_macro=0.9135
Epoch 32/50 train_loss=0.0002 val_loss=0.5141 val_acc=0.9121 val_f1_macro=0.9135
Epoch 33/50 train_loss=0.0001 val_loss=0.5159 val_acc=0.9121 val_f1_macro=0.9135
Epoch 34/50 train_loss=0.0001 val_loss=0.5180 val_acc=0.9121 val_f1_macro=0.9135
Epoch 35/50 train_loss=0.0001 val_loss=0.5243 val_acc=0.9121 val_f1_macro=0.9135
Epoch 36/50 train_loss=0.0001 val_loss=0.5257 val_acc=0.9121 val_f1_macro=0.9135
Epoch 37/50 train_loss=0.0001 val_loss=0.5341 val_acc=0.9121 val_f1_macro=0.9135
Epoch 38/50 train_loss=0.0001 val_loss=0.5353 val_acc=0.9121 val_f1_macro=0.9135
Epoch 39/50 train_loss=0.0001 val_loss=0.5375 val_acc=0.9145 val_f1_macro=0.9160
Epoch 40/50 train_loss=0.0001 val_loss=0.5424 val_acc=0.9145 val_f1_macro=0.9160
Epoch 41/50 train_loss=0.0001 val_loss=0.5460 val_acc=0.9145 val_f1_macro=0.9160
Epoch 42/50 train_loss=0.0001 val_loss=0.5500 val_acc=0.9145 val_f1_macro=0.9160
Epoch 43/50 train_loss=0.0001 val_loss=0.5579 val_acc=0.9145 val_f1_macro=0.9160
Epoch 44/50 train_loss=0.0001 val_loss=0.5592 val_acc=0.9145 val_f1_macro=0.9160
Epoch 45/50 train_loss=0.0001 val_loss=0.5595 val_acc=0.9121 val_f1_macro=0.9144
Epoch 46/50 train_loss=0.0001 val_loss=0.5600 val_acc=0.9097 val_f1_macro=0.9092
Epoch 47/50 train_loss=0.0001 val_loss=0.5676 val_acc=0.9121 val_f1_macro=0.9144
Epoch 48/50 train_loss=0.0001 val_loss=0.5719 val_acc=0.9145 val_f1_macro=0.9160
Epoch 49/50 train_loss=0.0000 val_loss=0.5742 val_acc=0.9145 val_f1_macro=0.9160
Epoch 50/50 train_loss=0.0000 val_loss=0.5785 val_acc=0.9121 val_f1_macro=0.9144
Saved baseline outputs to /kaggle/working/results/experiments/vit_s16_imagenet
{'accuracy': 0.9063231850117096, 'precision_macro': 0.9063575971799291, 'recall_macro': 0.915217990935954, 'f1_macro': 0.9085747518771936, 'precision_weighted': 0.9084951105110217, 'recall_weighted': 0.9063231850117096, 'f1_weighted': 0.9056268435083494, 'best_epoch': 8, 'best_val_f1_macro': 0.9184064180728325}

,experiment_id,accuracy,precision_macro,recall_macro,f1_macro,precision_weighted,recall_weighted,f1_weighted,best_epoch,best_val_f1_macro
0,vit_s16_imagenet,0.906323,0.906358,0.915218,0.908575,0.908495,0.906323,0.905627,8,0.918406

## 12. Summary Table

In [ ]:
rows = []
for exp in ['resnet18_none', 'resnet18_imagenet', 'vit_s16_none', 'vit_s16_imagenet']:
    metrics_path = OUTPUT_ROOT / exp / 'metrics.json'
    if metrics_path.exists():
        metrics = json.loads(metrics_path.read_text())
        rows.append({'experiment_id': exp, **metrics})

summary = pd.DataFrame(rows)
if len(summary):
    display(summary)
    summary_path = OUTPUT_ROOT / 'supervised_baseline_summary.csv'
    summary.to_csv(summary_path, index=False)
    print('Saved:', summary_path)
else:
    print('No completed baseline metrics found yet.')

,experiment_id,accuracy,precision_macro,recall_macro,f1_macro,precision_weighted,recall_weighted,f1_weighted,best_epoch,best_val_f1_macro
0,resnet18_none,0.882904,0.909286,0.890551,0.898092,0.884380,0.882904,0.881625,49,0.874358
1,resnet18_imagenet,0.939110,0.957435,0.950671,0.953937,0.939285,0.939110,0.939060,36,0.932232
2,vit_s16_none,0.777518,0.827831,0.762732,0.786988,0.785965,0.777518,0.772104,40,0.820963
3,vit_s16_imagenet,0.906323,0.906358,0.915218,0.908575,0.908495,0.906323,0.905627,8,0.918406

Saved: /kaggle/working/results/experiments/supervised_baseline_summary.csv

## 13. Package Results

Kaggle output files can be downloaded from `/kaggle/working`. This cell creates one zip archive for the baseline outputs.

In [ ]:
zip_base = Path('/kaggle/working/supervised_baseline_results')
if zip_base.with_suffix('.zip').exists():
    zip_base.with_suffix('.zip').unlink()
shutil.make_archive(str(zip_base), 'zip', root_dir=OUTPUT_ROOT.parent, base_dir='experiments')
print('Created:', zip_base.with_suffix('.zip'))

Created: /kaggle/working/supervised_baseline_results.zip